import fs from 'fs'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../../styles/Home.module.css'
import { remark } from 'remark';
import html from 'remark-html';
import matter from "gray-matter";

type Hoge = {
  contentHtml: string,
  matterResult: any
}

export async function getStaticPaths() {
  return {
    paths: [
      { params: {
        id: '1'
      } }
    ],
    fallback: false // false or 'blocking'
  };
}

export const getStaticProps = async () => {
  const article = fs.readFileSync('./public/articles/01.md')
  // Use gray-matter to parse the post metadata section
  const matterResult = matter(article);

  // Use remark to convert markdown into HTML string
  const processedContent = await remark()
    .use(html)
    .process(matterResult.content);
  const contentHtml = processedContent.toString();

  return  {
    props: {
      contentHtml
    }
  }
}

const Home: NextPage<Hoge> = ({ matterResult, contentHtml }) => {
  useEffect(() => {
  }, [])
  console.log(contentHtml)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div dangerouslySetInnerHTML={{ __html: contentHtml }} />
      </main>
    </div>
  )
}

export default Home
