import fs from 'fs'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'

type Hoge = {
  article: string  
}

export const getStaticProps = async () => {
  const article = String(fs.readFileSync('./public/articles/01.md'))
  return  {
    props: {
      article
    }
  }
}

const Home: NextPage<Hoge> = ({ article }) => {
  useEffect(() => {
    console.log('iwjefblwie')
  }, [])
  console.log(article)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>ブログだお</h1>
      </main>
    </div>
  )
}

export default Home
